# Generated by Django 5.2.5 on 2025-10-12 17:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("observations", "0001_initial"),
        ("referentials", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Construction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "project_name",
                    models.CharField(max_length=250, verbose_name="Project name"),
                ),
                ("location", models.CharField(max_length=250, verbose_name="Location")),
                (
                    "description",
                    models.TextField(max_length=1000, verbose_name="Description"),
                ),
                (
                    "num_housing_units",
                    models.IntegerField(
                        default=0,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Number housing units",
                    ),
                ),
                (
                    "num_adapted_units",
                    models.IntegerField(
                        default=0,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Number adapted units",
                    ),
                ),
                (
                    "land_area",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Land area"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Is active"),
                ),
                (
                    "observations",
                    models.ManyToManyField(
                        related_name="constructions",
                        to="observations.observation",
                        verbose_name="Observations",
                    ),
                ),
                (
                    "referentials",
                    models.ManyToManyField(
                        related_name="constructions",
                        to="referentials.referential",
                        verbose_name="",
                    ),
                ),
            ],
        ),
    ]
