# Generated by Django 5.2.5 on 2025-10-12 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("constructions", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="construction",
            name="land_area",
        ),
        migrations.RemoveField(
            model_name="construction",
            name="num_adapted_units",
        ),
        migrations.RemoveField(
            model_name="construction",
            name="num_housing_units",
        ),
    ]
