# Generated by Django 5.2.5 on 2025-11-08 15:26

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("constructions", "0002_remove_construction_land_area_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="construction",
            name="aprovation_observations",
            field=models.TextField(
                blank=True, max_length=5000, verbose_name="Aprovation observations"
            ),
        ),
        migrations.AddField(
            model_name="construction",
            name="aprovation_status",
            field=models.BooleanField(default=False, verbose_name="Aprovation status"),
        ),
        migrations.AddField(
            model_name="construction",
            name="creation_date",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="Creation date"
            ),
        ),
    ]
