# Generated by Django 5.2.5 on 2025-09-11 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("observations", "__first__"),
        ("referentials", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="StandardModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=250, verbose_name="Standard name"),
                ),
                ("num_housing_units", models.IntegerField(default=0)),
                ("num_adapted_units", models.IntegerField(default=0)),
                ("land_area", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "observations",
                    models.ManyToManyField(
                        related_name="standard_models", to="observations.observation"
                    ),
                ),
                (
                    "referentials",
                    models.ManyToManyField(
                        related_name="standard_models", to="referentials.referential"
                    ),
                ),
            ],
        ),
    ]
