# Generated by Django 5.2.5 on 2025-08-29 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Material",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type_of_material",
                    models.CharField(max_length=50, verbose_name="type_of_material"),
                ),
                ("brands", models.CharField(max_length=255, verbose_name="brands")),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="description"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
