# Generated by Django 5.2.5 on 2025-09-04 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("material", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="material",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
