# Generated by Django 5.2.5 on 2025-09-04 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("observation", "0002_observation_created_at_observation_updated_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="observation",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
