# Generated by Django 5.2.5 on 2025-09-11 22:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("areas", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ReferentialName",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Referential",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_approved", models.BooleanField(default=False)),
                ("comment", models.TextField(blank=True, max_length=500)),
                (
                    "areas",
                    models.ManyToManyField(
                        related_name="referentials", to="areas.area"
                    ),
                ),
                (
                    "referential_name",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="referentials",
                        to="referentials.referentialname",
                    ),
                ),
            ],
        ),
    ]
