# Generated by Django 5.2.5 on 2025-09-11 22:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("areas", "0001_initial"),
        ("elements", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="area",
            name="elements",
            field=models.ManyToManyField(related_name="areas", to="elements.element"),
        ),
        migrations.AddField(
            model_name="area",
            name="area_name",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="areas",
                to="areas.areaname",
            ),
        ),
    ]
